# services:
services:
  # --- CAPA DE ALMACENAMIENTO (COCKROACHDB) ---
  roach1:
    image: cockroachdb/cockroach:v23.1.10
    command: start --insecure --join=roach1,roach2,roach3 --listen-addr=roach1:26257 --advertise-addr=roach1:26257
    ports:
      - "8080:8080" # Consola Web en el puerto 8080
    volumes:
      - roach1_data:/cockroach/cockroach-data

  roach2:
    image: cockroachdb/cockroach:v23.1.10
    command: start --insecure --join=roach1,roach2,roach3 --listen-addr=roach2:26257 --advertise-addr=roach2:26257
    ports:
      - "8081:8080" # Consola Web en el puerto 8081 (opcional, para ver el nodo 2 directamente)
    volumes:
      - roach2_data:/cockroach/cockroach-data

  roach3:
    image: cockroachdb/cockroach:v23.1.10
    command: start --insecure --join=roach1,roach2,roach3 --listen-addr=roach3:26257 --advertise-addr=roach3:26257
    ports:
      - "8082:8080" # Consola Web en el puerto 8082
    volumes:
      - roach3_data:/cockroach/cockroach-data

  init:
    image: cockroachdb/cockroach:v23.1.10
    command: init --insecure --host=roach1:26257
    depends_on:
      - roach1
      - roach2
      - roach3

  # --- CAPA DE RED (BALANCEADORES HAPROXY) ---
  lb_norte:
    image: haproxy:2.8-alpine
    ports:
      - "26001:26257" # Tu Node.js del Norte se conectará al localhost:26001
    volumes:
      - ./haproxy-norte.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - roach1
      - roach2
      - roach3

  lb_centro:
    image: haproxy:2.8-alpine
    ports:
      - "26002:26257" # Tu Node.js del Centro se conectará al localhost:26002
    volumes:
      - ./haproxy-centro.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - roach1
      - roach2
      - roach3

  lb_sur:
    image: haproxy:2.8-alpine
    ports:
      - "26003:26257" # Tu Node.js del Sur se conectará al localhost:26003
    volumes:
      - ./haproxy-sur.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - roach1
      - roach2
      - roach3

volumes:
  roach1_data:
  roach2_data:
  roach3_data:
  

  # servercentral:
  #   build: ./serverCentral
  #   container_name: server_central
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     databasecentral:
  #       condition: service_healthy
  #     brokercentral:
  #       condition: service_healthy
  #   networks:
  #     regionCentral:
  #       aliases:
  #         - servercentral

  # serversur:
  #   build: ./serverSur
  #   container_name: server_sur
  #   restart: always
  #   ports:
  #     - "3001:3000"
  #   depends_on:
  #     databasesur:
  #       condition: service_healthy
  #     brokersur:
  #       condition: service_healthy
  #   networks:
  #     regionSur:
  #       aliases:
  #         - serversur
  
  # servernorte:
  #   build: ./serverNorte
  #   container_name: server_norte
  #   restart: always
  #   ports:
  #     - "3002:3000"
  #   depends_on:
  #     databasenorte:
  #       condition: service_healthy
  #     brokernorte:
  #       condition: service_healthy
  #   networks:
  #     regionNorte:
  #       aliases:
  #         - servernorte
  
  # brokercentral:
  #   image: eclipse-mosquitto:2.0.18
  #   container_name: broker-mosquitto-central
  #   ports:
  #     - "1881:1883"
  #   volumes:
  #     - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  #   networks:
  #     regionCentral:
  #       aliases:
  #         - brokercentral
  #   healthcheck:
  #     test: ["CMD-SHELL", "mosquitto_sub -h localhost -p 1883 -t '$$SYS/broker/version' -C 1 || exit 1"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  # brokersur:
  #   image: eclipse-mosquitto:2.0.18
  #   container_name: broker-mosquitto-sur
  #   ports:
  #     - "1882:1883"
  #   volumes:
  #     - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  #   networks:
  #     regionSur:
  #       aliases:
  #         - brokersur
  #   healthcheck:
  #     test: ["CMD-SHELL", "mosquitto_sub -h localhost -p 1883 -t '$$SYS/broker/version' -C 1 || exit 1"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  # brokernorte:
  #   image: eclipse-mosquitto:2.0.18
  #   container_name: broker-mosquitto-norte
  #   ports:
  #     - "1883:1883"
  #   volumes:
  #     - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  #   networks:
  #     regionNorte:
  #       aliases:
  #         - brokernorte
  #   healthcheck:
  #     test: ["CMD-SHELL", "mosquitto_sub -h localhost -p 1883 -t '$$SYS/broker/version' -C 1 || exit 1"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

networks: 
  regionSur:
    name: regionSur
    driver: bridge
  regionNorte:
    name: regionNorte
    driver: bridge
  regionCentral:
    name: regionCentral
    driver: bridge