services:
  # ==========================================
  # CAPA DE ALMACENAMIENTO (COCKROACHDB)
  # ==========================================
  roach1:
    image: cockroachdb/cockroach:v23.1.10
    command: start --insecure --join=roach1,roach2,roach3 --listen-addr=roach1:26257 --advertise-addr=roach1:26257
    ports:
      - "8080:8080"
    volumes:
      - roach1_data:/cockroach/cockroach-data
    networks:
      - cluster_db

  roach2:
    image: cockroachdb/cockroach:v23.1.10
    command: start --insecure --join=roach1,roach2,roach3 --listen-addr=roach2:26257 --advertise-addr=roach2:26257
    ports:
      - "8081:8080"
    volumes:
      - roach2_data:/cockroach/cockroach-data
    networks:
      - cluster_db

  roach3:
    image: cockroachdb/cockroach:v23.1.10
    command: start --insecure --join=roach1,roach2,roach3 --listen-addr=roach3:26257 --advertise-addr=roach3:26257
    ports:
      - "8082:8080"
    volumes:
      - roach3_data:/cockroach/cockroach-data
    networks:
      - cluster_db

  init:
    image: cockroachdb/cockroach:v23.1.10
    command: init --insecure --host=roach1:26257
    depends_on:
      - roach1
      - roach2
      - roach3
    networks:
      - cluster_db

  # ==========================================
  # CAPA DE RED (BALANCEADORES HAPROXY)
  # ==========================================
  lb_norte:
    image: haproxy:2.8-alpine
    ports:
      - "26001:26257"
    volumes:
      - ./haproxy-norte.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - roach1
      - roach2
      - roach3
    networks:
      - cluster_db
      - regionNorte # Puente hacia la región Norte

  lb_centro:
    image: haproxy:2.8-alpine
    ports:
      - "26002:26257"
    volumes:
      - ./haproxy-centro.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - roach1
      - roach2
      - roach3
    networks:
      - cluster_db
      - regionCentral # Puente hacia la región Centro

  lb_sur:
    image: haproxy:2.8-alpine
    ports:
      - "26003:26257"
    volumes:
      - ./haproxy-sur.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - roach1
      - roach2
      - roach3
    networks:
      - cluster_db
      - regionSur # Puente hacia la región Sur

  # ==========================================
  # CAPA DE INGESTA (BROKERS MQTT)
  # ==========================================
  brokernorte:
    image: eclipse-mosquitto:2.0.18
    container_name: broker-mosquitto-norte
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - regionNorte
    healthcheck:
      # Usa netcat (nc) para intentar abrir una conexión TCP rápida al puerto 1883
      test: ["CMD", "nc", "-z", "localhost", "1883"]
      interval: 5s
      timeout: 3s
      retries: 3

  brokercentro:
    image: eclipse-mosquitto:2.0.18
    container_name: broker-mosquitto-centro
    ports:
      - "1884:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - regionCentral
    healthcheck:
      # Usa netcat (nc) para intentar abrir una conexión TCP rápida al puerto 1883
      test: ["CMD", "nc", "-z", "localhost", "1883"]
      interval: 5s
      timeout: 3s
      retries: 3

  brokersur:
    image: eclipse-mosquitto:2.0.18
    container_name: broker-mosquitto-sur
    ports:
      - "1885:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - regionSur
    healthcheck:
      # Usa netcat (nc) para intentar abrir una conexión TCP rápida al puerto 1883
      test: ["CMD", "nc", "-z", "localhost", "1883"]
      interval: 5s
      timeout: 3s
      retries: 3

  # ==========================================
  # CAPA DE SERVICIOS (SERVIDORES NODE.JS)
  # ==========================================
  api_norte:
    build: 
      context: ./backend-logistica # Todos usan el mismo código
    container_name: server_norte
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://root@lb_norte:26257/logistica_flotilla?sslmode=disable
      - MQTT_BROKER_URL=mqtt://brokernorte:1883
      - REGION_ID=NORTE
      - JWT_SECRET=complex_secret_key_for_jwt_logistic_system
    volumes:
      - ./backend-logistica/src:/usr/src/app/src
    depends_on:
      lb_norte:
        condition: service_started
      brokernorte:
        condition: service_healthy
    networks:
      - regionNorte

  # api_centro:
  #   build: 
  #     context: ./backend-logistica
  #   container_name: server_central
  #   ports:
  #     - "3001:3000" # Exponemos el 3001 a tu compu, pero adentro corre en el 3000
  #   environment:
  #     - PORT=3000
  #     - DATABASE_URL=postgresql://root@lb_centro:26257/logistica_flotilla?sslmode=disable
  #     - MQTT_BROKER_URL=mqtt://brokercentro:1883
  #     - REGION_ID=CENTRO
  #     - JWT_SECRET=complex_secret_key_for_jwt_logistic_system
  #   volumes:
  #     - ./backend-logistica/src:/usr/src/app/src
  #   depends_on:
  #     lb_centro:
  #       condition: service_started
  #     brokercentro:
  #       condition: service_healthy
  #   networks:
  #     - regionCentral

  # api_sur:
  #   build: 
  #     context: ./backend-logistica
  #   container_name: server_sur
  #   ports:
  #     - "3002:3000" # Exponemos el 3002 a tu compu
  #   environment:
  #     - PORT=3000
  #     - DATABASE_URL=postgresql://root@lb_sur:26257/logistica_flotilla?sslmode=disable
  #     - MQTT_BROKER_URL=mqtt://brokersur:1883
  #     - REGION_ID=SUR
  #     - JWT_SECRET=complex_secret_key_for_jwt_logistic_system
  #   volumes:
  #     - ./backend-logistica/src:/usr/src/app/src
  #   depends_on:
  #     lb_sur:
  #       condition: service_started
  #     brokersur:
  #       condition: service_healthy
  #   networks:
  #     - regionSur

# ==========================================
# DEFINICIÓN DE VOLÚMENES Y REDES
# ==========================================
volumes:
  roach1_data:
  roach2_data:
  roach3_data:

networks:
  cluster_db:
    name: cluster_db
    driver: bridge
  regionNorte:
    name: regionNorte
    driver: bridge
  regionCentral:
    name: regionCentral
    driver: bridge
  regionSur:
    name: regionSur
    driver: bridge